// <auto-generated />
namespace PatheUpcomingMovies.DetailApi
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Detail
    {
        [JsonProperty("responseHeader")]
        public ResponseHeader ResponseHeader { get; set; }

        [JsonProperty("response")]
        public Response Response { get; set; }
    }

    public partial class Response
    {
        [JsonProperty("numFound")]
        public long NumFound { get; set; }

        [JsonProperty("start")]
        public long Start { get; set; }

        [JsonProperty("docs")]
        public List<Doc> Docs { get; set; }
    }

    public partial class Doc
    {
        [JsonProperty("synopsis_en", NullValueHandling = NullValueHandling.Ignore)]
        public string SynopsisEn { get; set; }

        [JsonProperty("title_fr")]
        public string TitleFr { get; set; }

        [JsonProperty("title_fr_s")]
        public string TitleFrS { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("title_s")]
        public string TitleS { get; set; }

        [JsonProperty("type")]
        public TypeEnum Type { get; set; }

        [JsonProperty("oneline_en", NullValueHandling = NullValueHandling.Ignore)]
        public string OnelineEn { get; set; }

        [JsonProperty("duration")]
        public long Duration { get; set; }

        [JsonProperty("cast", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Cast { get; set; }

        [JsonProperty("genre", NullValueHandling = NullValueHandling.Ignore)]
        public List<Genre> Genre { get; set; }

        [JsonProperty("id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Id { get; set; }

        [JsonProperty("synopsis_fr", NullValueHandling = NullValueHandling.Ignore)]
        public string SynopsisFr { get; set; }

        [JsonProperty("director", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Director { get; set; }

        [JsonProperty("oneline_de", NullValueHandling = NullValueHandling.Ignore)]
        public string OnelineDe { get; set; }

        [JsonProperty("trailer_embed_ov", NullValueHandling = NullValueHandling.Ignore)]
        public string TrailerEmbedOv { get; set; }

        [JsonProperty("cast_voice")]
        public bool CastVoice { get; set; }

        [JsonProperty("release_de_ch", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? ReleaseDeCh { get; set; }

        [JsonProperty("oneline_fr", NullValueHandling = NullValueHandling.Ignore)]
        public string OnelineFr { get; set; }

        [JsonProperty("title_de")]
        public string TitleDe { get; set; }

        [JsonProperty("title_de_s")]
        public string TitleDeS { get; set; }

        [JsonProperty("lang_ov")]
        public LangOv LangOv { get; set; }

        [JsonProperty("release_fr_ch", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? ReleaseFrCh { get; set; }

        [JsonProperty("synopsis_de", NullValueHandling = NullValueHandling.Ignore)]
        public string SynopsisDe { get; set; }

        [JsonProperty("_version_")]
        public double Version { get; set; }

        [JsonProperty("trailer_embed_de", NullValueHandling = NullValueHandling.Ignore)]
        public string TrailerEmbedDe { get; set; }

        [JsonProperty("poster_de", NullValueHandling = NullValueHandling.Ignore)]
        public string PosterDe { get; set; }

        [JsonProperty("poster_fr", NullValueHandling = NullValueHandling.Ignore)]
        public string PosterFr { get; set; }

        [JsonProperty("trailer_embed_fr", NullValueHandling = NullValueHandling.Ignore)]
        public string TrailerEmbedFr { get; set; }

        [JsonProperty("poster_ov", NullValueHandling = NullValueHandling.Ignore)]
        public string PosterOv { get; set; }

        [JsonProperty("cast_de", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> CastDe { get; set; }

        [JsonProperty("cast_fr", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> CastFr { get; set; }
    }

    public partial class ResponseHeader
    {
        [JsonProperty("zkConnected")]
        public bool ZkConnected { get; set; }

        [JsonProperty("status")]
        public long Status { get; set; }

        [JsonProperty("QTime")]
        public long QTime { get; set; }

        [JsonProperty("params")]
        public Params Params { get; set; }
    }

    public partial class Params
    {
        [JsonProperty("fq")]
        public string Fq { get; set; }

        [JsonProperty("_")]
        public string Empty { get; set; }
    }

    public enum Genre { Action, Adventure, Animation, Comedy, Crime, Docu, Drama, Family, Fantasy, Horror, Music, Musical, Mystery, Romance, Scifi, Thriller };

    public enum LangOv { Ar, Da, De, En, Es, Fr, Hi, Is, It, Pt, Ru, Zh };

    public enum TypeEnum { Movie };

    public partial class Detail
    {
        public static Detail FromJson(string json) => JsonConvert.DeserializeObject<Detail>(json, PatheUpcomingMovies.DetailApi.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Detail self) => JsonConvert.SerializeObject(self, PatheUpcomingMovies.DetailApi.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                GenreConverter.Singleton,
                LangOvConverter.Singleton,
                TypeEnumConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class GenreConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Genre) || t == typeof(Genre?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "action":
                    return Genre.Action;
                case "adventure":
                    return Genre.Adventure;
                case "animation":
                    return Genre.Animation;
                case "comedy":
                    return Genre.Comedy;
                case "crime":
                    return Genre.Crime;
                case "docu":
                    return Genre.Docu;
                case "drama":
                    return Genre.Drama;
                case "family":
                    return Genre.Family;
                case "fantasy":
                    return Genre.Fantasy;
                case "horror":
                    return Genre.Horror;
                case "music":
                    return Genre.Music;
                case "musical":
                    return Genre.Musical;
                case "mystery":
                    return Genre.Mystery;
                case "romance":
                    return Genre.Romance;
                case "scifi":
                    return Genre.Scifi;
                case "thriller":
                    return Genre.Thriller;
            }
            throw new Exception("Cannot unmarshal type Genre");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Genre)untypedValue;
            switch (value)
            {
                case Genre.Action:
                    serializer.Serialize(writer, "action");
                    return;
                case Genre.Adventure:
                    serializer.Serialize(writer, "adventure");
                    return;
                case Genre.Animation:
                    serializer.Serialize(writer, "animation");
                    return;
                case Genre.Comedy:
                    serializer.Serialize(writer, "comedy");
                    return;
                case Genre.Crime:
                    serializer.Serialize(writer, "crime");
                    return;
                case Genre.Docu:
                    serializer.Serialize(writer, "docu");
                    return;
                case Genre.Drama:
                    serializer.Serialize(writer, "drama");
                    return;
                case Genre.Family:
                    serializer.Serialize(writer, "family");
                    return;
                case Genre.Fantasy:
                    serializer.Serialize(writer, "fantasy");
                    return;
                case Genre.Horror:
                    serializer.Serialize(writer, "horror");
                    return;
                case Genre.Music:
                    serializer.Serialize(writer, "music");
                    return;
                case Genre.Musical:
                    serializer.Serialize(writer, "musical");
                    return;
                case Genre.Mystery:
                    serializer.Serialize(writer, "mystery");
                    return;
                case Genre.Romance:
                    serializer.Serialize(writer, "romance");
                    return;
                case Genre.Scifi:
                    serializer.Serialize(writer, "scifi");
                    return;
                case Genre.Thriller:
                    serializer.Serialize(writer, "thriller");
                    return;
            }
            throw new Exception("Cannot marshal type Genre");
        }

        public static readonly GenreConverter Singleton = new GenreConverter();
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }

    internal class LangOvConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(LangOv) || t == typeof(LangOv?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "ar":
                    return LangOv.Ar;
                case "da":
                    return LangOv.Da;
                case "de":
                    return LangOv.De;
                case "en":
                    return LangOv.En;
                case "es":
                    return LangOv.Es;
                case "fr":
                    return LangOv.Fr;
                case "hi":
                    return LangOv.Hi;
                case "is":
                    return LangOv.Is;
                case "it":
                    return LangOv.It;
                case "pt":
                    return LangOv.Pt;
                case "ru":
                    return LangOv.Ru;
                case "zh":
                    return LangOv.Zh;
            }
            throw new Exception("Cannot unmarshal type LangOv");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (LangOv)untypedValue;
            switch (value)
            {
                case LangOv.Ar:
                    serializer.Serialize(writer, "ar");
                    return;
                case LangOv.Da:
                    serializer.Serialize(writer, "da");
                    return;
                case LangOv.De:
                    serializer.Serialize(writer, "de");
                    return;
                case LangOv.En:
                    serializer.Serialize(writer, "en");
                    return;
                case LangOv.Es:
                    serializer.Serialize(writer, "es");
                    return;
                case LangOv.Fr:
                    serializer.Serialize(writer, "fr");
                    return;
                case LangOv.Hi:
                    serializer.Serialize(writer, "hi");
                    return;
                case LangOv.Is:
                    serializer.Serialize(writer, "is");
                    return;
                case LangOv.It:
                    serializer.Serialize(writer, "it");
                    return;
                case LangOv.Pt:
                    serializer.Serialize(writer, "pt");
                    return;
                case LangOv.Ru:
                    serializer.Serialize(writer, "ru");
                    return;
                case LangOv.Zh:
                    serializer.Serialize(writer, "zh");
                    return;
            }
            throw new Exception("Cannot marshal type LangOv");
        }

        public static readonly LangOvConverter Singleton = new LangOvConverter();
    }

    internal class TypeEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(TypeEnum) || t == typeof(TypeEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "movie")
            {
                return TypeEnum.Movie;
            }
            throw new Exception("Cannot unmarshal type TypeEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (TypeEnum)untypedValue;
            if (value == TypeEnum.Movie)
            {
                serializer.Serialize(writer, "movie");
                return;
            }
            throw new Exception("Cannot marshal type TypeEnum");
        }

        public static readonly TypeEnumConverter Singleton = new TypeEnumConverter();
    }
}
