// <auto-generated />
namespace PatheUpcomingMovies.UpcomingApi
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Upcoming
    {
        [JsonProperty("responseHeader")]
        public ResponseHeader ResponseHeader { get; set; }

        [JsonProperty("response")]
        public Response Response { get; set; }

        [JsonProperty("facet_counts")]
        public FacetCounts FacetCounts { get; set; }
    }

    public partial class FacetCounts
    {
        [JsonProperty("facet_queries")]
        public Facet FacetQueries { get; set; }

        [JsonProperty("facet_fields")]
        public FacetFields FacetFields { get; set; }

        [JsonProperty("facet_ranges")]
        public Facet FacetRanges { get; set; }

        [JsonProperty("facet_intervals")]
        public Facet FacetIntervals { get; set; }

        [JsonProperty("facet_heatmaps")]
        public Facet FacetHeatmaps { get; set; }

        [JsonProperty("facet_pivot")]
        public FacetPivot FacetPivot { get; set; }
    }

    public partial class FacetFields
    {
        [JsonProperty("movie_id")]
        public List<List<long>> MovieId { get; set; }
    }

    public partial class Facet
    {
    }

    public partial class FacetPivot
    {
        [JsonProperty("preview,movie_id")]
        public List<PreMovieId> PreviewMovieId { get; set; }

        [JsonProperty("presale,movie_id")]
        public List<PreMovieId> PresaleMovieId { get; set; }
    }

    public partial class PreMovieId
    {
        [JsonProperty("field")]
        public PresaleMovieIdField Field { get; set; }

        [JsonProperty("value")]
        public bool Value { get; set; }

        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("pivot")]
        public List<Pivot> Pivot { get; set; }
    }

    public partial class Pivot
    {
        [JsonProperty("field")]
        public PivotField Field { get; set; }

        [JsonProperty("value")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Value { get; set; }

        [JsonProperty("count")]
        public long Count { get; set; }
    }

    public partial class Response
    {
        [JsonProperty("numFound")]
        public long NumFound { get; set; }

        [JsonProperty("start")]
        public long Start { get; set; }

        [JsonProperty("docs")]
        public List<Doc> Docs { get; set; }
    }

    public partial class Doc
    {
        [JsonProperty("release_date")]
        public DateTimeOffset ReleaseDate { get; set; }

        [JsonProperty("preview")]
        public bool Preview { get; set; }

        [JsonProperty("site")]
        public Site Site { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("movie_id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long MovieId { get; set; }

        [JsonProperty("type")]
        public TypeEnum Type { get; set; }

        [JsonProperty("presale")]
        public bool Presale { get; set; }

        [JsonProperty("_version_")]
        public double Version { get; set; }
    }

    public partial class ResponseHeader
    {
        [JsonProperty("zkConnected")]
        public bool ZkConnected { get; set; }

        [JsonProperty("status")]
        public long Status { get; set; }

        [JsonProperty("QTime")]
        public long QTime { get; set; }

        [JsonProperty("params")]
        public Params Params { get; set; }
    }

    public partial class Params
    {
        [JsonProperty("fq")]
        public string Fq { get; set; }

        [JsonProperty("_")]
        public string Empty { get; set; }
    }

    public enum PresaleMovieIdField { Presale, Preview };

    public enum PivotField { MovieId };

    public enum Site { Bal, Die, Flo, Gal, Kuc, Mos, Spe, Wes };

    public enum TypeEnum { Upcoming };

    public partial class Upcoming
    {
        public static Upcoming FromJson(string json) => JsonConvert.DeserializeObject<Upcoming>(json, PatheUpcomingMovies.UpcomingApi.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Upcoming self) => JsonConvert.SerializeObject(self, PatheUpcomingMovies.UpcomingApi.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                PresaleMovieIdFieldConverter.Singleton,
                PivotFieldConverter.Singleton,
                SiteConverter.Singleton,
                TypeEnumConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class DecodingChoiceConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            switch (reader.TokenType)
            {
                case JsonToken.Integer:
                    var integerValue = serializer.Deserialize<long>(reader);
                    return integerValue;
                case JsonToken.String:
                case JsonToken.Date:
                    var stringValue = serializer.Deserialize<string>(reader);
                    long l;
                    if (Int64.TryParse(stringValue, out l))
                    {
                        return l;
                    }
                    break;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value);
            return;
        }

        public static readonly DecodingChoiceConverter Singleton = new DecodingChoiceConverter();
    }

    internal class PresaleMovieIdFieldConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(PresaleMovieIdField) || t == typeof(PresaleMovieIdField?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "presale":
                    return PresaleMovieIdField.Presale;
                case "preview":
                    return PresaleMovieIdField.Preview;
            }
            throw new Exception("Cannot unmarshal type PresaleMovieIdField");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (PresaleMovieIdField)untypedValue;
            switch (value)
            {
                case PresaleMovieIdField.Presale:
                    serializer.Serialize(writer, "presale");
                    return;
                case PresaleMovieIdField.Preview:
                    serializer.Serialize(writer, "preview");
                    return;
            }
            throw new Exception("Cannot marshal type PresaleMovieIdField");
        }

        public static readonly PresaleMovieIdFieldConverter Singleton = new PresaleMovieIdFieldConverter();
    }

    internal class PivotFieldConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(PivotField) || t == typeof(PivotField?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "movie_id")
            {
                return PivotField.MovieId;
            }
            throw new Exception("Cannot unmarshal type PivotField");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (PivotField)untypedValue;
            if (value == PivotField.MovieId)
            {
                serializer.Serialize(writer, "movie_id");
                return;
            }
            throw new Exception("Cannot marshal type PivotField");
        }

        public static readonly PivotFieldConverter Singleton = new PivotFieldConverter();
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }

    internal class SiteConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Site) || t == typeof(Site?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "BAL":
                    return Site.Bal;
                case "DIE":
                    return Site.Die;
                case "FLO":
                    return Site.Flo;
                case "GAL":
                    return Site.Gal;
                case "KUC":
                    return Site.Kuc;
                case "MOS":
                    return Site.Mos;
                case "SPE":
                    return Site.Spe;
                case "WES":
                    return Site.Wes;
            }
            throw new Exception("Cannot unmarshal type Site");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Site)untypedValue;
            switch (value)
            {
                case Site.Bal:
                    serializer.Serialize(writer, "BAL");
                    return;
                case Site.Die:
                    serializer.Serialize(writer, "DIE");
                    return;
                case Site.Flo:
                    serializer.Serialize(writer, "FLO");
                    return;
                case Site.Gal:
                    serializer.Serialize(writer, "GAL");
                    return;
                case Site.Kuc:
                    serializer.Serialize(writer, "KUC");
                    return;
                case Site.Mos:
                    serializer.Serialize(writer, "MOS");
                    return;
                case Site.Spe:
                    serializer.Serialize(writer, "SPE");
                    return;
                case Site.Wes:
                    serializer.Serialize(writer, "WES");
                    return;
            }
            throw new Exception("Cannot marshal type Site");
        }

        public static readonly SiteConverter Singleton = new SiteConverter();
    }

    internal class TypeEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(TypeEnum) || t == typeof(TypeEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "upcoming")
            {
                return TypeEnum.Upcoming;
            }
            throw new Exception("Cannot unmarshal type TypeEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (TypeEnum)untypedValue;
            if (value == TypeEnum.Upcoming)
            {
                serializer.Serialize(writer, "upcoming");
                return;
            }
            throw new Exception("Cannot marshal type TypeEnum");
        }

        public static readonly TypeEnumConverter Singleton = new TypeEnumConverter();
    }
}
