name: Update Pathe Upcoming Movies

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * MON'

jobs:
  update-calendars:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'
          cache: 'pip'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Update EN calendar
        run: ./pathe_upcoming_movies.py --country CH --language EN --output ./calendars/PatheUpcomingMovies_EN.ics

      - name: Update FR calendar
        run: ./pathe_upcoming_movies.py --country CH --language FR --output ./calendars/PatheUpcomingMovies_FR.ics

      - name: Update DE calendar
        run: ./pathe_upcoming_movies.py --country CH --language DE --output ./calendars/PatheUpcomingMovies_DE.ics

      - name: Update EN calendar (FR site)
        run: ./pathe_upcoming_movies.py --country FR --language EN --output ./calendars/PatheUpcomingMovies_EN_FR.ics

      - name: Update FR calendar (FR site)
        run: ./pathe_upcoming_movies.py --country FR --language FR --output ./calendars/PatheUpcomingMovies_FR_FR.ics

      - name: Update DE calendar (FR site)
        run: ./pathe_upcoming_movies.py --country FR --language DE --output ./calendars/PatheUpcomingMovies_DE_FR.ics

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          fetch: true
          default_author: github_actions
          message: Update EN, FR and DE calendars
          pathspec_error_handling: exitImmediately
          push: true
